name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set executable permissions for gradlew
        run: chmod +x backend/EasyMoneyMapApi/gradlew

      - name: Build Backend
        run: |
          cd backend/EasyMoneyMapApi
          ./gradlew build

      - name: Run Backend Tests
        run: |
          cd backend/easyMoneyApi
          ./gradlew test

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Get Flutter Dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Run Flutter Tests
        run: |
          cd frontend
          flutter test
